In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import numpy.random as random
from sklearn.tree import DecisionTreeClassifier

In [2]:
from scikit_weak import *

In [3]:
X, y = load_iris(return_X_y=True)

In [4]:
np.random.seed(0)

noise = 0.10
target = []
for t in y:
    t_temp = [t]
    classes = np.unique(y)
    for c in classes:
        if random.uniform(size=1) <= noise and c != t:
            t_temp.append(c)
    target.append(DiscreteSetLabel(t_temp, 3))

In [10]:
rs = RoughSetSelector(search_strategy='approximate', epsilon = 0.1, discrete=True, n_iters=10)
rs.fit(X, target)
print(rs.reducts_)

[array([0, 3])]


In [9]:
rs = RoughSetSelector(search_strategy='brute', epsilon = 0.1, discrete=True)
rs.fit(X, target)
print(rs.reducts_)

[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [1 3]
 [2 3]]


In [11]:
rs = RoughSetSelector(search_strategy='brute', epsilon = 0.1, discrete=False,
                      neighborhood='delta', radius=0.1)
rs.fit(X, target)
print(rs.reducts_)

[[0 2]
 [0 3]
 [1 2]
 [1 3]
 [2 3]]


In [12]:
rs = RoughSetSelector(search_strategy='brute', epsilon = 0.1, discrete=False,
                      neighborhood='nearest', n_neighbors=10)
rs.fit(X, target)
print(rs.reducts_)

[[2]
 [3]]


In [13]:
clf = RRLClassifier(resample=True)
clf.fit(X, target)
accuracy_score(y, clf.predict(X))

0.9933333333333333

In [14]:
clf = WeaklySupervisedKNeighborsClassifier()
clf.fit(X, target)
accuracy_score(y, clf.predict(X))

0.9533333333333334

In [15]:
clf = DELIN()
clf.fit(X, target)
accuracy_score(y, clf.predict(X))

0.9733333333333334